# Generated by Django 4.1.2 on 2022-11-10 06:22

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("temp", models.CharField(max_length=225)),
                ("init", models.BooleanField(default=True)),
                ("budget_init", models.BooleanField(default=True)),
                (
                    "net_worth",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "dividends",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "interest",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "food",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "housing",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "transportation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "utilities",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "insurance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "medical",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "personal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "recreational",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "miscellaneous",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "leftOver",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "goalPrice",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=225)),
                ("name", models.TextField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_type", models.CharField(max_length=225)),
                ("date", models.DateField()),
                ("transaction_name", models.TextField()),
                ("remarks", models.CharField(max_length=225)),
                ("category", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "transaction_acct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.financialaccount",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SetAside",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.CharField(max_length=225)),
                ("goal_Name", models.CharField(max_length=225)),
                ("value", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "target_Duration",
                    models.DecimalField(decimal_places=0, max_digits=20),
                ),
                ("remarks", models.CharField(max_length=225)),
                (
                    "per_month",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
