# Generated by Django 4.1.2 on 2022-10-30 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.CharField(max_length=225)),
                ("goal_Name", models.CharField(max_length=225)),
                ("value", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "target_Duration",
                    models.DecimalField(decimal_places=0, max_digits=20),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
