# Generated by Django 4.1.3 on 2022-11-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='per_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
